#!/bin/bash
MYSHPATH=$(pwd)


ln -s $MYSHPATH/.xg_bash_aliases ~/.xg_bash_aliases

echo "
if [ -f ~/.xg_bash_aliases ]; then
	. ~/.xg_bash_aliases
fi">>~/.bashrc && source ~/.bashrc


echo "
if [ -f ~/.xg_bash_aliases ]; then
	. ~/.xg_bash_aliases
fi">>~/.zshrc && source ~/.zshrc
