#!/bin/bash
# LANG=zh_CN.UTF-8
# ##################################################################
# 2021年 09月 23日 星期四 00:56:14 CST
# Written by:xgz
# FileName:Shutdown 
# Usage:
# Contact me by linuxgz@163.com
# ##################################################################
shutdown -P +10
